language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
services: docker
install: pip install poetry tox-travis
script: tox
deploy:
  - provider: script
    script: poetry publish --build
    on:
      branch: master
      python: '3.8'
      tags: true
